# Makefile.config written by configure
OCAML_CORE_STDLIB=/home/labeip/.opam/4.00.1/lib/ocaml
OCAML_CORE_BIN=/home/labeip/.opam/4.00.1/bin
OCAML_CORE_MAN=/home/labeip/.opam/4.00.1/man
OCAML_SITELIB=/home/labeip/.opam/4.00.1/lib
OCAML_THREADS=posix
OCAMLFIND_BIN=/home/labeip/.opam/4.00.1/bin
OCAMLFIND_MAN=/home/labeip/.opam/4.00.1/man
OCAMLFIND_CONF=/home/labeip/.opam/4.00.1/lib/findlib.conf
OCAML_AUTOLINK=true
OCAML_REMOVE_DIRECTORY=1
EXEC_SUFFIX=
CUSTOM=-custom
PARTS=findlib
INSTALL_TOPFIND=1
USE_CYGPATH=0
VERSION=1.4
SYSTEM=linux
